### PR TITLE
Fix incorrect behaviour when vanilla 'make' is issued

### PR DESCRIPTION
**Pull request by roscopeco**

### CODE REVIEW

**Review by 0xTJ — DISMISSED** [review]
This fixes the issue. It might make sense to apply the same to 
[code/firmware/rosco_m68k_v1.3/Makefile](https://github.com/rosco-m68k/rosco_m68k/blob/feature/fix-broken-make/code/firmware/rosco_m68k_v1.3/Makefile) too, since that's still a non-attic version. I'll approve this anyways, up to you whether you merge this or change that one too first.

**Comment by roscopeco** [comment]
> This fixes the issue. It might make sense to apply the same to
> [code/firmware/rosco_m68k_v1.3/Makefile](https://github.com/rosco-m68k/rosco_m68k/blob/feature/fix-broken-make/code/firmware/rosco_m68k_v1.3/Makefile) too, since that's still a non-attic version. I'll approve this anyways, up to you whether you merge this or change that one too first.

Good call @0xTJ , I'll make that change and push it to this PR branch. Thanks :)

**Comment by roscopeco** [comment]
Thanks @0xTJ , I (finally) got around to doing this for FW1.3 makefile too :)

**Review by 0xTJ — APPROVED** [review]
Looks good! (Aside from the fact that it doesn't link yet without the other PR being pulled in😄)

**Pull request merged**
