### PR TITLE
Feature/release fw 2.1

### PR DESCRIPTION
**Pull request by roscopeco**
Release FW 2.1. This is a minor release:

* Fixes intermittent issue with blinking LED
* Use DUART timer mode
* Much better alloc support in libs
* Tidy ups

### CODE REVIEW

**Comment by 0xTJ** [comment]
Should the `code/firmware/rosco_m68k_v2.0` directory be renamed/copied to `code/firmware/rosco_m68k_v2.1` to keep the versions in sync?

**Comment by 0xTJ** [comment]
Also, it looks like there's an inconsistency with how versions are decoded. `RELEASE_VER` seems to use BCD, so this is version `0210`. `updateflash` instead uses the value directly, so it detects this ROM image as being version `2.16` instead of `2.10`.

**Comment by roscopeco** [comment]
Good spot @0xTJ , done on both counts :)

**Review by 0xTJ — APPROVED** [review]
Looks good to me 👍, most of the major changes are parts of previous PRs.

Those extra commits will probably need to be brought into develop too.

**Pull request merged**
